# Generated by Django 4.2.3 on 2023-07-18 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 23, 41, 10, 348790), verbose_name='дата истечения'),
        ),
    ]
