# Generated by Django 4.2.3 on 2023-07-21 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_comment_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 18, 53, 44, 436125), verbose_name='дата истечения'),
        ),
    ]
